AWSTemplateFormatVersion: '2010-09-09'
Description: 'Plantilla para crear grupo de seguridad y una instancia de aplicación'
Resources:
  ApplicationServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Grupo de Seguridad para el puerto 8080
      GroupName: AppServerSecurityGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  ApplicationServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: LabInstanceProfile
      ImageId: ami-0c7217cdde317cfec
      InstanceType: t2.micro
      SecurityGroupIds: 
        - !Ref ApplicationServerSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 8
            VolumeType: gp2 
            DeleteOnTermination: true
